
server:
  port: 8080
  ssl:
    key-store-password: mofit
    key-store-type: PKCS12
    key-store: classpath:keystore.p12

OPENVIDU_URL: https://ena.jegal.shop:8443/
OPENVIDU_SECRET: MY_SECRET

# Mysql연결 연결
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mydatabase.cuk71njgvznj.us-east-1.rds.amazonaws.com:3306/dev?serverTimezone=UTC&characterEncoding=UTF-8

    username: admin
    password: mofit123
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate.show_sql: true
        hibernate.format_sql: true

jwt:
  secret:
    key: bPeShVkYp3s6v9y$B&E)H@McQfTjWnZq4t7w!z%C*F-JaNdRgUkXp2s5u8x/A?D(G+KbPeShVmYq3t6w9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B
redis:
  host: mofit-redis
  port: 6379